### ISSUE TITLE
Last update page

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#28]
![last-guide-update](https://cloud.githubusercontent.com/assets/264708/13995152/412cfc80-f128-11e5-935e-7301567848c4.png).

The code can be found under https://github.com/padrino/padrino-web/tree/last-updated. All we have to do is to add the following in the frontmatter:

``` md

---
chapter: Getting Started
title: Basic Projects
updated: 2016-02-21

---
```

Don't know who to automate the thing to update the page. @angeloashmore what's your opinion?

**Comment by angeloashmore** [comment]
I removed the `updated` frontmatter from the documents because that data is already stored in Git and the file metadata itself. It would be something to manually update each time, which cannot be guaranteed to happen.

That being said, it would be helpful to include the date on the pages. Although not 100% foolproof, I think we could just look at the file's last modified timestamp and use that to display the last updated date.

**Comment by wikimatze** [comment]
Thanks for the feedback, after looking around for a while I found the following solution:

``` ruby
File.mtime(current_page.source_file).strftime("%Y-%m-%d")
```

which is 100% foolproof :).
