### ISSUE TITLE
Merge Blog Posts

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-web-new#6]
There are some blog posts in https://github.com/padrino/padrino-docs/tree/master/posts that are not in https://github.com/angeloashmore/padrino-web/tree/master/source/blog. We should consolidate all blog posts. Also, the blog posts in padrino-docs have the ["tags"](https://github.com/padrino/padrino-framework/blob/master/padrino-docs/posts/padrino-0-10-0-routing-upgrades-rbx-and-jruby-support-and-minor-breaking-changes.md) and other metadata stored while the ones in source do not.

**Comment by wikimatze** [comment]
I checked the tags in https://github.com/padrino/padrino-docs/tree/master/posts and compared them with https://github.com/padrino/padrino-web-new/tree/master/source/blog. They shoulb be fine now.

The missing blog-posts are:
- https://github.com/padrino/padrino-web-new/blob/master/source/blog/2014-10-16-padrino-0-12-4.md
- https://github.com/padrino/padrino-web-new/blob/master/source/blog/2015-09-10-padrino-0-12-5.md

I'll port them to the https://github.com/padrino/padrino-docs/tree/master/posts repository.

**Comment by wikimatze** [comment]
The issue is over with the following commits:
- https://github.com/padrino/padrino-docs/commit/31b3a68be99c6b8de7e7aaf3d53f743160fbfbc8
- https://github.com/padrino/padrino-docs/commit/7000140c330a589460a3d9ddf774e239997dcb86
- https://github.com/padrino/padrino-docs/commit/555e5beabf01ef4bb53f7344cb8b55657587a9d9
- https://github.com/padrino/padrino-docs/commit/4b7b53e951aec6e5546060001d4f089dbc95f6d1

**Comment by nesquena** [comment]
Yep this looks good. Thanks for merging these! Should we close this?

**Comment by wikimatze** [comment]
Glad that this issue is finally closed.
